version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - type: volume
        source: node-red-data
        target: /data

volumes:
  node-red-data: